version: "3.5"
services:
  az2:
    container_name: az2
    build:
      context: .
      dockerfile: Dockerfile.az2
    environment:
      - "TZ=Asia/Tokyo"
      - "TEST_ENV=1"
    volumes:
      - "workdir:/work:rw"
    networks:
      - default

volumes:
  workdir:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/work
      o: bind
